### ISSUE TITLE
Unnecessary promises?

### ISSUE THREAD

**Issue by bttmly** [omnibus-app/Omnibus#140]
What's going on [here](https://github.com/omnibus-app/Omnibus/blob/master/app%2Fscripts%2Fcontroller.coffee#L84-L101)? Doesn't look like anything async is happening. Why the deferreds?

**Comment by MSchip** [comment]
I can't tell exactly which one you're talking about, but if it's in
"getData" it needs to be there for when the data is grabbed from local
storage and not fetched through the model.

**Comment by bttmly** [comment]
The lines were highlighted in that link before I updated it; now the line numbers are all f'd up. It's fixed now. But some of the views were being created with promises when unnecessary. You can see the changes in [this commit](https://github.com/omnibus-app/Omnibus/commit/5ba8cc2e2cbaac43aa9d685408dc5b6c99dd8c62#diff-d41d8cd98f00b204e9800998ecf8427e)

**Comment by MSchip** [comment]
Ah, I see.  Yeah, at first I was hitting different end points with those
model views.  Never changed it back after I was receiving the data object
instead.

**Comment by bttmly** [comment]
Ah gotcha, ok. All fixed and pretty now
